app = "withered-thunder-3955" # set this as SERVERURL
primary_region = "bom"

# default kill-child for unshare(1)
# man7.org/linux/man-pages/man1/unshare.1.html
kill_signal = "SIGKILL"
kill_timeout = "20s"

[build]
  dockerfile = "./Dockerfile"

[env]
  LOG_CONFS = "true"
  PEERDNS = "auto"
  PEERS = "1"
  PGID = "1000"
  PUID = "1000"
  SERVERPORT = "51820"
  SERVERURL = "withered-thunder-3955.fly.dev"

[mounts]
  destination = "/config"
  source = "config"

[[services]]
  internal_port = 51820
  protocol = "udp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 51820
